import { use } from "react";
import { setRequestLocale } from "next-intl/server";
import { useCopy } from "@/i18n/copy";
import { pageMetadata } from "@/lib/metadata";
import { BuildingImage, ContactBand, PageIntro, TextLink } from "@/components/shared";
export async function generateMetadata({params}: {params: Promise<{locale: string}>}) {const {locale}=await params; setRequestLocale(locale); return pageMetadata("/about", "About Embuilded", "Embuilded Intelligence Limited connects field devices, operational data and evidence into practical systems for the built world.");}
export default function AboutPage({params}: {params: Promise<{locale: string}>}) {
 const {locale}=use(params); setRequestLocale(locale);
 const t = useCopy(); return <><PageIntro label={t("ABOUT EMBUILDED")} title={<>{t("Grounded in the field.")}<br />{t("Connected by intelligence.")}</>} description={t("Embuilded Intelligence Limited connects field devices, operational data and evidence into practical systems for construction, infrastructure and the wider built environment.")}/><section className="wrap about-feature"><BuildingImage /><div className="about-feature-copy"><h2>{t("Engineering meets")}<br />{t("connected operations.")}</h2><p>{t("Our work brings together field engineering, connected hardware integration and managed device services. TRACI is the technology platform connecting devices, intelligence and evidence.")}</p><TextLink href="/traci">{t("Meet TRACI")}</TextLink></div></section><section className="section wrap about-identity"><div><h2>{t("One company.")}<br />{t("A connected family.")}</h2><p className="mt-6">{t("A clear structure, from the engineering on site to the platform behind it.")}</p></div><ul className="identity-list"><li><strong>{t("Embuilded")}</strong><span>{t("The company")}</span></li><li><strong>{t("TRACI")}</strong><span>{t("The technology platform")}</span></li><li><strong>{t("TRACI plugins")}</strong><span>{t("Modular capabilities")}</span></li><li><strong>{t("Devices & solutions")}</strong><span>{t("Connected field systems")}</span></li><li><strong>{t("Embuilded Services")}</strong><span>{t("Engineering & managed services")}</span></li></ul></section><ContactBand title={t("Let\u2019s build the next connection.")}/></>; }
