import { FieldPhoto } from "@/components/field-photo";
import { use } from "react";
import { setRequestLocale } from "next-intl/server";
import { useCopy } from "@/i18n/copy";
import { pageMetadata } from "@/lib/metadata";
import { ContactBand, PageIntro, ServiceList } from "@/components/shared";
export async function generateMetadata({params}: {params: Promise<{locale: string}>}) {const {locale}=await params; setRequestLocale(locale); return pageMetadata("/services", "Engineering & managed services", "Field engineering, connected hardware integration and managed device/software services for the built world.");}
export default function ServicesPage({params}: {params: Promise<{locale: string}>}) {
 const {locale}=use(params); setRequestLocale(locale);
 const t = useCopy(); return <><PageIntro label={t("SERVICES")} title={<>{t("From the first survey")}<br />{t("to connected operations.")}</>} description={t("Three ways to work with Embuilded. Start with field engineering, combine it with hardware, or add managed device and software services.")}/><div className="wrap inner-field-photo"><FieldPhoto scene="crew"/></div><section className="wrap service-page-list" aria-label={t("Service options")}><ServiceList full/></section><section className="page-panel"><div className="wrap"><div className="section-heading"><h2>{t("A practical path from site to system.")}</h2></div><div className="process-grid"><article><span className="mono">{t("DISCOVER")}</span><h3>{t("Understand the field.")}</h3><p>{t("Work through the site, operating objectives and existing systems to establish a clear scope.")}</p></article><article><span className="mono">{t("CONNECT")}</span><h3>{t("Engineer the solution.")}</h3><p>{t("Bring together hardware, connectivity, installation and the required platform integration.")}</p></article><article><span className="mono">{t("OPERATE")}</span><h3>{t("Plan for the lifecycle.")}</h3><p>{t("Define commissioning, maintenance and managed service responsibilities around your operation.")}</p></article></div></div></section><ContactBand title={t("Start with the support you need.")}/></>; }
