import { FieldPhoto } from "@/components/field-photo";
import { use } from "react";
import { setRequestLocale } from "next-intl/server";
import { useCopy } from "@/i18n/copy";
import { pageMetadata } from "@/lib/metadata";
import { ArrowsLeftRight } from "@phosphor-icons/react/dist/ssr";
import { ActionLink, ContactBand, ServiceList } from "@/components/shared";
export async function generateMetadata({params}: {params: Promise<{locale: string}>}) {const {locale}=await params; setRequestLocale(locale); return pageMetadata("/partners", "Partner with Embuilded", "Keep your platform. Use Embuilded field engineering, connected hardware and managed infrastructure underneath it.");}
export default function PartnersPage({params}: {params: Promise<{locale: string}>}) {
 const {locale}=use(params); setRequestLocale(locale);
 const t = useCopy(); return <><div className="partner-hero"><section className="page-intro wrap"><div className="eyebrow">{t("PARTNERS")}</div><h1>{t("Keep your platform.")}<br /><span>{t("We connect the field.")}</span></h1><p>{t("Field engineering, connected devices and managed infrastructure for system integrators, AI and CCTV partners, and SSSS and 4S providers.")}</p><div className="intro-actions"><ActionLink href="/contact?service=Partnership">{t("Let\u2019s talk")}</ActionLink></div></section><div className="wrap partner-map"><article><h2>{t("Your platform")}</h2><p>{t("Software, workflows and the customer experience your team already delivers.")}</p></article><ArrowsLeftRight size={32} aria-hidden="true"/><article><h2>{t("Our infrastructure")}</h2><p>{t("Field engineering, connected hardware and managed device services underneath it.")}</p></article></div></div><div className="wrap inner-field-photo"><FieldPhoto scene="buildings"/></div><section className="section wrap services-grid"><div className="section-heading"><h2>{t("Choose where")}<br />{t("we fit.")}</h2><p>{t("Engineering only. Hardware with engineering. Or a managed device service. Define the engagement around your delivery model.")}</p></div><ServiceList /></section><section className="page-panel"><div className="wrap"><div className="section-heading"><h2>{t("Agree the interfaces.")}<br />{t("Keep responsibilities clear.")}</h2><p>{t("Align field scope, hardware responsibilities, platform interfaces and ongoing support before deployment.")}</p></div><div className="process-grid"><article><h3>{t("Field delivery")}</h3><p>{t("Site survey, camera positioning, connectivity, cabling, mounting and commissioning.")}</p></article><article><h3>{t("System integration")}</h3><p>{t("Scope API, MQTT and webhook integration around your existing platform.")}</p></article><article><h3>{t("Lifecycle support")}</h3><p>{t("Define device health, diagnostics, configuration and maintenance responsibilities.")}</p></article></div></div></section><ContactBand title={t("Build the next connection together.")} description={t("Tell us about your platform and where you need support in the field.")}/></>; }
